#!/usr/bin/env python3
"""Materialize this plugin's generated Codex agents into a project or user dir.

Codex plugin installation copies a plugin bundle; it does not interpret this
repository's host manifest as a custom-agent installation step. This explicit,
idempotent bootstrap is therefore required after adding the plugin.
"""
import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
import render_agents  # noqa: E402


def materialize(target, plugin_root=ROOT):
    host = render_agents.load_host("codex")
    roles = render_agents.load_roles()
    target = Path(target).expanduser().resolve()
    target.mkdir(parents=True, exist_ok=True)
    expected = set()
    for role_file, role in roles:
        name = role["id"] + ".toml"
        expected.add(name)
        content = render_agents.render_toml(
            role, dict(host, root_placeholder=str(Path(plugin_root).resolve())), role_file
        )
        destination = target / name
        temporary = destination.with_name(destination.name + ".tmp")
        temporary.write_text(content, encoding="utf-8")
        temporary.replace(destination)

    # Remove only files previously generated by this installer. Never remove
    # unrelated user agents in the selected directory.
    marker = target / ".root-architect-execution-codex.json"
    previous = set()
    if marker.exists():
        try:
            state = json.loads(marker.read_text(encoding="utf-8"))
            previous = set(state.get("files", []))
        except (OSError, ValueError, AttributeError):
            previous = set()
    for name in previous - expected:
        candidate = target / name
        if candidate.is_file():
            candidate.unlink()
    marker.write_text(json.dumps({"version": 1, "files": sorted(expected)},
                                 indent=2) + "\n", encoding="utf-8")
    return target, sorted(expected)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", default=".codex/agents",
                        help="project or user Codex agent directory")
    parser.add_argument("--plugin-root", default=str(ROOT),
                        help="installed plugin root used in generated references")
    args = parser.parse_args(argv)
    target, names = materialize(args.target, args.plugin_root)
    print("materialized %d Codex agents in %s" % (len(names), target))
    for name in names:
        print("  %s" % (target / name))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
