#!/usr/bin/env python3
"""Generate host agent files from the role manifests in roles/.

The role manifests are the only place a role's model tier, reasoning strength,
tool grant, and mutation class are written down; the prose lives once under
references/agents/. Everything under agents/ (and any other host's agent
directory) is generated from those two sources and must never be hand-edited.

The rule that makes this worth having: a capability the host cannot express is
never silently dropped. It is written into an "Enforcement" section of the
generated file, marked unenforced, and reported by --check. A brief that claims
host-enforced isolation it does not have is worse than one that admits the
instruction is all there is.

    render_agents.py --host claude-code --out agents
    render_agents.py --host claude-code --out agents --check
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from jsonschema_mini import Validator  # noqa: E402
from return_shape import skeleton  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS = ROOT / "schemas"

# A quality finding needs a failure scenario, which the schema cannot mark
# required for only one of the two roles that share it. Show it anyway.
EXTRA_FIELDS = {"quality-validator": {"failure_scenario"}}


def return_skeleton(role):
    return skeleton(SCHEMAS / role["returns"],
                    extra=EXTRA_FIELDS.get(role["role"], ()),
                    pin={"role": role["role"]})


BANNER = ("GENERATED by scripts/render_agents.py from roles/{role_file} and "
          "hosts/{host}.json. Do not edit by hand; edit the role manifest and "
          "regenerate.")


def load_roles():
    validator = Validator(SCHEMAS / "agent-role.schema.json")
    roles = []
    for path in sorted((ROOT / "roles").glob("*.json")):
        role = json.loads(path.read_text(encoding="utf-8"))
        errors = validator.validate(role)
        if "run-commands" in role.get("tools", {}).get("allow", []):
            if not role["tools"].get("shell_purpose"):
                errors.append("$.tools.shell_purpose: required when the grant "
                              "includes run-commands")
        if errors:
            raise SystemExit("roles/%s is not schema-conformant:\n  %s"
                             % (path.name, "\n  ".join(errors)))
        roles.append((path.name, role))
    return roles


def load_host(name):
    path = ROOT / "hosts" / ("%s.json" % name)
    if not path.exists():
        raise SystemExit("no host manifest at %s" % path)
    host = json.loads(path.read_text(encoding="utf-8"))
    errors = Validator(SCHEMAS / "host-capability.schema.json").validate(host)
    for key, cap in host.get("capabilities", {}).items():
        if cap.get("supported") and not cap.get("field"):
            errors.append("$.capabilities.%s.field: required when supported" % key)
    if host["capabilities"]["reasoning_effort"]["supported"] and not host.get("effort_map"):
        errors.append("$.effort_map: required when reasoning_effort is supported")
    if errors:
        raise SystemExit("hosts/%s.json is not schema-conformant:\n  %s"
                         % (name, "\n  ".join(errors)))
    return host


def resolve_tools(role, host):
    """Map portable intents to host tool names, collecting what cannot map."""
    tool_map = host["tool_map"]
    allow, deny, unmappable = [], [], []
    for intent in role["tools"]["allow"]:
        names = tool_map.get(intent)
        if not names:
            unmappable.append(intent)
            continue
        for name in names:
            if name not in allow:
                allow.append(name)
    for intent in role["tools"]["deny"]:
        for name in tool_map.get(intent, []):
            if name not in deny and name not in allow:
                deny.append(name)
    return allow, deny, unmappable


def disclosures(role, host, unmappable):
    """Every guarantee this host will not enforce, stated plainly."""
    caps = host["capabilities"]
    out = []
    if not caps["tool_allowlist"]["supported"]:
        out.append(
            "Tool grant is **not enforced** on this host: %s has no per-agent "
            "tool allowlist, so the grant stated above is an instruction only."
            % host["host"])
    if unmappable:
        out.append(
            "These portable tool intents have no mapping on this host and are "
            "instructions only: %s." % ", ".join(sorted(unmappable)))
    if role["mutation"] == "read-only" and not caps["read_only_enforced"]["supported"]:
        out.append(
            "Read-only is **not enforced** on this host. Do not describe this "
            "agent as isolated; it is a read-only instruction.")
    if role["mutation"] == "write-scoped":
        out.append(
            "Write scope is **never** host-enforced anywhere: no host limits "
            "edits to a brief's write paths. The boundary holds because the "
            "agent honours it and root reviews the diff against it.")
    if not caps["reasoning_effort"]["supported"]:
        out.append(
            "Reasoning strength is not settable on this host. Record effort as "
            "'not settable on this host' rather than naming a level nothing "
            "applied.")
    else:
        mapped = host["effort_map"]
        folded = sorted({lvl for lvl in ([role["reasoning"]["default"]]
                                         + role["reasoning"]["escalation"])
                         if mapped.get(lvl) != lvl})
        if folded:
            out.append(
                "This host's effort scale is coarser than the manifest's: %s."
                % "; ".join("%s is applied as %s" % (lvl, mapped[lvl])
                            for lvl in folded))
    if not caps["scoped_hooks"]["supported"]:
        out.append(
            "Per-agent hooks are unavailable on this host, so the prohibitions "
            "stated above rely on session-wide hooks or on the agent's own "
            "compliance.")
    return out


def render_markdown_yaml(role, host, role_file):
    caps = host["capabilities"]
    prefix = host.get("root_placeholder", "<skill_root>")
    allow, deny, unmappable = resolve_tools(role, host)
    lines = ["---", "name: %s" % role["id"],
             "description: %s" % role["description"]]

    model = host["model_map"][role["model"]["default"]]
    effort = None
    if caps["reasoning_effort"]["supported"]:
        effort = host["effort_map"][role["reasoning"]["default"]]
    if caps["reasoning_effort"].get("field") == caps["explicit_model"].get("field"):
        # Cursor encodes effort inside the model string rather than beside it.
        lines.append("%s: %s[effort=%s]" % (caps["explicit_model"]["field"],
                                            model, effort))
    else:
        lines.append("%s: %s" % (caps["explicit_model"]["field"], model))
        if effort is not None:
            lines.append("%s: %s" % (caps["reasoning_effort"]["field"], effort))

    if caps["tool_allowlist"]["supported"]:
        lines.append("%s: %s" % (caps["tool_allowlist"]["field"], ", ".join(allow)))
    if caps["tool_denylist"]["supported"] and deny:
        lines.append("%s: %s" % (caps["tool_denylist"]["field"], ", ".join(deny)))
    if (role["mutation"] == "read-only"
            and caps["read_only_enforced"]["supported"]
            and caps["read_only_enforced"]["field"] not in
            (caps["tool_allowlist"].get("field"), None)):
        lines.append("%s: true" % caps["read_only_enforced"]["field"])
    lines.append("---")

    lines += ["", "<!-- %s -->" % BANNER.format(role_file=role_file,
                                            host=host["host"]), "",
              "# Role — %s" % role["role"], "",
              "Read `%s/%s` before doing anything. It is the canonical "
              "definition of this role and it governs you; this file carries "
              "only the host frontmatter and the disclosures below."
              % (prefix, role["prose"]), "",
              "Return exactly one fenced `json` block in this shape, and "
              "nothing else. Root validates it mechanically before reading it; "
              "a malformed return is sent back once.", "",
              "```json", return_skeleton(role), "```", "",
              "Placeholders show the type; `a|b` means pick one. The full "
              "contract, including the optional fields, is "
              "`%s/schemas/%s`." % (prefix, role["returns"]), ""]

    lines += ["## Grant", "",
              "Capability class: **%s**." % role["mutation"], ""]
    lines.append("Allowed: %s." % ", ".join(allow))
    if deny:
        lines.append("Denied: %s." % ", ".join(deny))
    if role["tools"].get("shell_purpose"):
        lines += ["", "Shell purpose — the only reason a shell exists for you: %s"
                  % role["tools"]["shell_purpose"]]
    lines += ["", "## Never", "",
              "You must never: %s." % ", ".join(sorted(role["must_not"])), ""]

    notes = disclosures(role, host, unmappable)
    lines += ["## Enforcement", ""]
    if notes:
        lines.append("What this host does *not* enforce for you:")
        lines.append("")
        lines += ["- %s" % note for note in notes]
    else:
        lines.append("Every declared capability is enforced by the host itself.")
    lines.append("")
    return "\n".join(lines)


def render_toml(role, host, role_file):
    caps = host["capabilities"]
    prefix = host.get("root_placeholder", "<skill_root>")
    allow, deny, unmappable = resolve_tools(role, host)
    notes = disclosures(role, host, unmappable)
    body = [
        "Read %s/%s before doing anything. It is the canonical "
        "definition of this role and it governs you." % (prefix, role["prose"]),
        "",
        "Return exactly one fenced json block in this shape, and nothing "
        "else. Placeholders show the type; a|b means pick one. The full "
        "contract is %s/schemas/%s." % (prefix, role["returns"]),
        "",
        return_skeleton(role),
        "",
        "Capability class: %s. Allowed: %s." % (role["mutation"], ", ".join(allow)),
    ]
    if deny:
        body.append("Denied: %s." % ", ".join(deny))
    if role["tools"].get("shell_purpose"):
        body.append("Shell purpose: %s" % role["tools"]["shell_purpose"])
    body.append("You must never: %s." % ", ".join(sorted(role["must_not"])))
    if notes:
        body.append("")
        body.append("Not enforced by this host:")
        body += ["- %s" % note.replace("**", "") for note in notes]

    lines = ["# %s" % BANNER.format(role_file=role_file, host=host["host"]),
             'name = "%s"' % role["id"],
             'description = "%s"' % role["description"].replace('"', "'"),
             '%s = "%s"' % (caps["explicit_model"]["field"],
                            host["model_map"][role["model"]["default"]])]
    if caps["reasoning_effort"]["supported"]:
        lines.append('%s = "%s"' % (caps["reasoning_effort"]["field"],
                                    host["effort_map"][role["reasoning"]["default"]]))
    if role["mutation"] == "read-only" and caps["read_only_enforced"]["supported"]:
        lines.append('%s = "read-only"' % caps["read_only_enforced"]["field"])
    lines.append('developer_instructions = """')
    lines += body
    lines.append('"""')
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="claude-code")
    parser.add_argument("--out", default=None,
                        help="output directory; defaults to the host manifest's "
                             "agent_dir, resolved inside the plugin")
    parser.add_argument("--check", action="store_true",
                        help="regenerate in memory and fail if what is on disk "
                             "differs, instead of writing")
    args = parser.parse_args(argv)

    host = load_host(args.host)
    out_dir = Path(args.out) if args.out else ROOT / host["bundled_dir"]
    extension = ".toml" if host["format"] == "toml" else ".md"
    render = render_toml if host["format"] == "toml" else render_markdown_yaml

    drifted, written = [], []
    for role_file, role in load_roles():
        content = render(role, host, role_file)
        target = out_dir / (role["id"] + extension)
        if args.check:
            current = target.read_text(encoding="utf-8") if target.exists() else None
            if current != content:
                drifted.append(str(target))
            continue
        out_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(str(target))

    if args.check:
        if drifted:
            print("out of sync with roles/ and hosts/%s.json:" % args.host,
                  file=sys.stderr)
            for path in drifted:
                print("  %s" % path, file=sys.stderr)
            print("run: render_agents.py --host %s" % args.host, file=sys.stderr)
            return 1
        print("in sync: %s agent files match roles/ and hosts/%s.json"
              % (len(load_roles()), args.host))
        return 0

    for path in written:
        print("wrote %s" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
